import type { Project } from './types';

export const about = {
  name: 'Wolf',
  title: 'Full-Stack Developer & Founder',
  brand: 'Foxy Tech',
  location: 'Kenya',
  partner: 'Casper Tech Kenya',
  bio: 'I build bots, streaming platforms, and APIs that push the limits of what\'s possible. Founder of Foxy Tech — crafting technology that\'s fast, bold, and powerful.',
  bio2: 'From WhatsApp bots to cyberpunk streaming sites, everything I build carries the Foxy Tech DNA: neon-lit, performant, and built to last.',
  skills: [
    'Node.js', 'React', 'TypeScript', 'JavaScript',
    'Express.js', 'Python', 'REST APIs', 'WebSockets',
    'Telegram Bots', 'WhatsApp Automation', 'Supabase',
    'Streaming Tech', 'Cyberpunk UI', 'Git / GitHub',
  ],
  github: 'https://github.com/wolfix-bots',
};

export const projects: Project[] = [
  {
    id: 'foxystream',
    name: 'FoxyStream',
    description: 'Cyberpunk movie & TV streaming web app with AI-curated genre rows, episode picker, quality selector, inline trailer player, and fullscreen landscape lock.',
    tags: ['React', 'TypeScript', 'Tailwind', 'xcasper API'],
    color: 'cyan',
    url: 'https://foxystream.onrender.com',
    github: 'https://github.com/wolfix-bots/cyber-stream-foxy',
    icon: '🎬',
  },
  {
    id: 'foxyflix',
    name: 'FoxyFlix',
    description: 'Lightweight vanilla JS streaming SPA. Zero framework — pure DOM, pure performance. Full movie & TV browsing with HD quality selection.',
    tags: ['Vanilla JS', 'Node.js', 'Express'],
    color: 'magenta',
    url: '#',
    github: 'https://github.com/wolfix-bots/foxyflix',
    icon: '🦊',
  },
  {
    id: 'foxy-api',
    name: 'Foxy API',
    description: 'The backbone of the entire Foxy ecosystem. 85+ REST API endpoints powering all bots and streaming platforms. Fast, reliable, always on.',
    tags: ['Node.js', 'Express', 'REST API', '85+ endpoints'],
    color: 'cyan',
    url: 'https://foxy-api-febf.onrender.com',
    github: 'https://github.com/wolfix-bots/foxy-api',
    icon: '⚡',
  },
  {
    id: 'webfoxy',
    name: 'WebFoxy',
    description: 'WhatsApp automation bot that delivers movie info, stream links, and bot services directly in WhatsApp chat. Full production deployment.',
    tags: ['WhatsApp', 'Node.js', 'Bot', 'WhatsApp Web.js'],
    color: 'magenta',
    url: '#',
    github: 'https://github.com/wolfix-bots/Webfoxy',
    icon: '💬',
  },
  {
    id: 'foxy-ig',
    name: 'Foxy IG',
    description: 'Instagram bot panel — a clean web-based control panel for managing and operating automated Instagram interactions.',
    tags: ['Instagram', 'Node.js', 'Bot Panel'],
    color: 'cyan',
    url: '#',
    github: 'https://github.com/wolfix-bots/foxy-ig',
    icon: '📸',
  },
  {
    id: 'foxy-telegram',
    name: 'Foxy Bot Telegram',
    description: 'Telegram bot management dashboard. Control, monitor, and operate the Foxy Telegram bot ecosystem from a clean web interface.',
    tags: ['Telegram', 'Bot', 'Node.js', 'Dashboard'],
    color: 'magenta',
    url: '#',
    github: '#',
    icon: '✈️',
  },
];
